import { GoogleGenAI } from "@google/genai";
import type { RepoData } from "../types";

const ai = new GoogleGenAI({ apiKey: import.meta.env.VITE_API_KEY });

const createPrompt = (data: RepoData): string => {
    const { repoDetails, rootFiles, packageJsonContent } = data;

    const fileList = rootFiles.map(file => `${file.name}${file.type === 'dir' ? '/' : ''}`).join(', ');

    let prompt = `
You are an expert technical writer specializing in creating high-quality README.md files for software projects.
Your task is to generate a comprehensive and well-structured README.md file in Markdown format based on the provided GitHub repository information.

**Repository Information:**
- **Name:** ${repoDetails.name}
- **Description:** ${repoDetails.description || 'No description provided.'}
- **Main Language:** ${repoDetails.language || 'Not specified.'}
- **Root Directory Files:** ${fileList}
${packageJsonContent ? `- **package.json contents:** \n\`\`\`json\n${packageJsonContent}\n\`\`\`\n` : ''}

**Instructions:**
Generate a complete README.md file with the following sections. Be creative and infer the project's purpose from the file names and repository information.

1.  **Project Title:** Use the repository name as the main H1 title.
2.  **Badges:** Add relevant badges (e.g., from shields.io). Include a license badge and a top language badge.
3.  **Description:** Expand on the provided description. If it's missing, create an engaging summary based on the repository name and files.
4.  **Features:** Create a bulleted list of potential key features.
5.  **Tech Stack:** List the technologies, languages, and frameworks used. Infer from \`package.json\` if available, otherwise use the repo file extensions like.py,.js.
6.  **Installation:** Provide clear, step-by-step instructions on how to clone the repository and install dependencies. If it's a Node.js project, first mention \`npm install\`.
7.  **Usage:** Explain how to run or use the project (e.g., \`npm start\`). If not obvious, provide a generic example.
8.  **Contributing:** Include a standard section inviting contributions and outlining the basic process (fork, create branch, pull request).
9.  **License:** State the license of the project. It is licensed under the ${repoDetails.license?.name || 'MIT License'}.

**Output Rules:**
- The entire output MUST be in valid Markdown format.
- Do not include any text, explanations, or code block specifiers like \`\`\`markdown before or after the main Markdown content.
- Start directly with the H1 project title (e.g., '# Project Name').
- Make the README visually appealing and easy to read.
`;

    return prompt.trim();
};

export const generateReadme = async (repoData: RepoData): Promise<string> => {
    const prompt = createPrompt(repoData);

    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: prompt,
            config: {
                temperature: 0.4,
                topP: 0.95,
                topK: 64,
            },
        });
        // Extract the generated text from the Gemini API response
        // For @google/genai v1.x, the text is in response.candidates[0].content.parts[0].text
        const text = response?.candidates?.[0]?.content?.parts?.[0]?.text;
        if (!text) throw new Error("No README content generated by Gemini.");
        return text;
    } catch (error) {
        console.error("Error generating README with Gemini:", error);
        throw new Error("Failed to generate README. The AI model could not process the request.");
    }
};
